# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - motomini_arm_controller
    - end_effector_controller

  motomini_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t
    action_ns: follow_joint_trajectory
    default: true
  end_effector_controller:
    type: GripperCommand
    joints:
      []
    action_ns: gripper_cmd
    default: true